# Generated by Django 4.0.3 on 2022-07-19 12:54

import api.submodels.company
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyModel',
            fields=[
                ('name', models.CharField(help_text='Name of the company', max_length=50)),
                ('exchange', models.CharField(help_text='Symbol used on the market (ASX for Australian Stock Exchange)', max_length=20)),
                ('symbol', models.CharField(help_text='Symbol to be used on the market (eg FMG.AX for Fortescue on ASX)', max_length=20, primary_key=True, serialize=False)),
                ('market_cap', models.BigIntegerField()),
                ('last_updated', models.DateTimeField(default=api.submodels.company.two_years_ago)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_companies', models.BooleanField(default=False)),
                ('indicators', models.CharField(default='{}', max_length=1000)),
                ('company_list', models.ManyToManyField(to='api.companymodel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.IntegerField()),
                ('dividends', models.FloatField()),
                ('stock_splits', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.companymodel')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
